accounts/urls.py
from django.conf.urls import url

from .views import ProfileSettingsView

urlpatterns = [
    url(r'^settings/$', ProfileSettingsView.as_view(), name='settings'),

]

easyreservation/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'next_page': '/login/'},
        name='logout'
        ),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
    url('api/users/',
        include('accounts.api.urls', namespace='users-api')
        ),
    url('api/resources/',
        include('resources.api.urls', namespace='resources-api')
        ),
    url('api/reservations/',
        include('reservations.api.urls', namespace='reservations-api')
        ),

    url('accounts/', include('accounts.urls', namespace='accounts')),

    url('resources/', include('resources.urls', namespace='resources')),
    url('reservations/',
        include('reservations.urls', namespace='reservations')),
    url(r'', include('reservations.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT
                          )
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

reservations/api/urls.py
from django.conf.urls import url

from .views import (
    ReservationCreateAPIView,
    ReservationListAPIView,
    ReservationDetailAPIView,
    ReservationDestroyAPIView,
    ReservationUpdateAPIView
)

urlpatterns = [
    url(
        r'^$',
        ReservationListAPIView.as_view(),
        name='list'
    ),
    url(
        r'^create/$',
        ReservationCreateAPIView.as_view(),
        name='create'
    ),
    url(
        r'^(?P<pk>[\w-]+)/details/$',
        ReservationDetailAPIView.as_view(),
        name='details'
    ),
    url(
        r'^(?P<pk>[\w-]+)/edit/$',
        ReservationUpdateAPIView.as_view(),
        name='update'
    ),
    url(
        r'^(?P<pk>[\w-]+)/delete/$',
        ReservationDestroyAPIView  .as_view(),
        name='delete'
    ),
]

reservations/urls.py
from django.conf.urls import url

from .views import (
    ReservationAddView,
    ReservationListView,
    ReservationEditView,
)

urlpatterns = [
    url(r'^$', ReservationListView.as_view(), name='list'),
    url(r'^create/', ReservationAddView.as_view(), name='new'),
    url(r'(?P<pk>[\w-]+)/detail/', ReservationEditView.as_view(), name='detail'),

]

reservations/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _

from django.db import models

from resources.models import Resource
from django.contrib.auth.models import User

# Create your models here.


class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    resource = models.ForeignKey(
        to=Resource,
        db_column='resource',
        related_name='reservations',
        verbose_name=_('resource'),
        db_constraint=False,
        on_delete=models.CASCADE,
        default=None
    )

    title = models.CharField(max_length=120, verbose_name=_('title'),)
    reservation_time = models.CharField(max_length=120,
                                        blank=True,
                                        verbose_name=_('Reservation Time'),
                                        )

    time_zone = models.CharField(max_length=120,
                                 blank=True,
                                 verbose_name=_('time_zone')
                                 )

    class Meta(object):
        managed = True
        db_table = 'reservations'

reservations/forms.py
from django import forms
from .models import Reservation

# Create the form class.


class ReservationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ReservationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})


    class Meta:
        model = Reservation
        fields = ['title', 'resource', 'reservation_time']

reservations/api/views.py
from datetime import datetime
import pytz

from django.utils.timezone import localtime
from django.utils import timezone

from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    UpdateAPIView,
    RetrieveAPIView,
)

from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly
)

from reservations.models import Reservation
from accounts.models import Profile

from .permissions import isOwnerOrAdmin

from .serializers import (
    ReservationSerializer,
    ReservationCreateUpdateSerializer,
)


class ReservationCreateAPIView(CreateAPIView):
    queryset = Reservation.objects.all()
    serializer_class = ReservationCreateUpdateSerializer
    permission_classes = [IsAuthenticated, isOwnerOrAdmin]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class ReservationDetailAPIView(RetrieveAPIView):
    queryset = Reservation.objects.all()

    serializer_class = ReservationSerializer
    permission_classes = [IsAuthenticated, isOwnerOrAdmin]


    def get_object(self, *args, **kwargs):
        obj = super(ReservationDetailAPIView, self).get_object(*args, **kwargs)
        if self.request.session.get('django_timezone'):
            tzname = self.request.session.get('django_timezone')
        else:
            tzname = Profile.objects.filter(user=self.request.user).first().time_zone
            self.request.session['django_timezone'] = tzname
        if tzname:
            timezone.activate(pytz.timezone(tzname))
        else:
            timezone.deactivate()
        dates = obj.reservation_time.split(' - ')
        time_zone = obj.time_zone
        if time_zone:
            tz = pytz.timezone(time_zone)
        else:
            tz = pytz.timezone('UTC')
        local_tz = pytz.timezone(tzname)
        start = local_tz.localize(
            datetime.strptime(dates[0], '%m/%d/%Y %I:%M %p'))
        end = local_tz.localize(
            datetime.strptime(dates[1], '%m/%d/%Y %I:%M %p'))
        obj.reservation_time = str(
            localtime(start, tz).strftime('%m/%d/%Y %I:%M %p')) \
                               + ' - ' \
                               + str(localtime(end, tz)
                                     .strftime('%m/%d/%Y %I:%M %p')
                                     )
        return obj


class ReservationUpdateAPIView(UpdateAPIView):
    queryset = Reservation.objects.all()
    serializer_class = ReservationCreateUpdateSerializer
    permission_classes = [IsAuthenticated, isOwnerOrAdmin]


class ReservationDestroyAPIView(DestroyAPIView):
    queryset = Reservation.objects.all()
    serializer_class = ReservationSerializer
    permission_classes = [IsAuthenticated, isOwnerOrAdmin]


class ReservationListAPIView(ListAPIView):
    serializer_class = ReservationSerializer
    permission_classes = [IsAuthenticated]

    @method_decorator(cache_page(60))
    def dispatch(self, *args, **kwargs):
        return super(ReservationListAPIView, self).dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser:
            queryset_list = Reservation.objects.all()
        else:
            queryset_list = Reservation.objects.all().filter(
                user=self.request.user.id
            )
        reservations = list(queryset_list)
        for res in reservations:
           if self.request.session.get('django_timezone'):
               tzname = self.request.session.get('django_timezone')
           elif Profile.objects.filter(user=self.request.user).first().time_zone:
               tzname = Profile.objects.filter(user=self.request.user).first().time_zone
               self.request.session['django_timezone'] = tzname
           else:
               tzname='UTC'
           if tzname:
               timezone.activate(pytz.timezone(tzname))
           else:
               timezone.deactivate()

           dates = res.reservation_time.split(' - ')
           time_zone = res.time_zone
           if time_zone:
               tz = pytz.timezone(time_zone)
           else:
               tz = pytz.timezone('UTC')

           local_tz = pytz.timezone(tzname)
           start = local_tz.localize(datetime.strptime(dates[0], '%m/%d/%Y %I:%M %p'))
           end = local_tz.localize(datetime.strptime(dates[1], '%m/%d/%Y %I:%M %p'))
           res.reservation_time = str(
               localtime(start, tz).strftime('%m/%d/%Y %I:%M %p'))\
                                  + ' - '\
                                  + str(localtime(end, tz)
                                        .strftime('%m/%d/%Y %I:%M %p')
                                        )

        return reservations

reservations/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.detail import DetailView

from django.views import View
from django.views.generic.edit import CreateView

from django.shortcuts import render
from django.shortcuts import get_object_or_404


from .forms import ReservationForm
from .models import Reservation
from accounts.models import Profile
from resources.models import Resource


class ReservationAddView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    template_name = "reservation_form.html"
    form_class = ReservationForm
    success_url = '/reservations/'

    def get_initial(self, *args, **kwargs):
        if self.request.GET.get('resource_id') and self.request.method=="GET":
            pk = self.request.GET.get('resource_id')
            resource = get_object_or_404(Resource, pk=pk)
            return {'resource': resource}

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        instance = form.save()
        instance.user = self.request.user
        if self.request.session.get('django_timezone'):
            instance.time_zone = self.request.session.get('django_timezone')
        else:
            instance.time_zone = Profile.objects.filter(
                user=self.request.user).first().time_zone

        instance.save()
        return super(ReservationAddView, self).form_valid(form)


class ReservationEditView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    queryset = Reservation.objects.all()
    template_name = "reservation_details.html"
    success_url = '/reservations/'


class ReservationListView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'reservations_list.html')

templates/base.html
{% load staticfiles %}
{% load i18n %}

<!doctype html>
<html style="height: 100%;"  class="no-js h-100" lang="en" ng-app="easyreservation">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Easy Reservation</title>
    <meta name="description" content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head_css %}
      <!-- Bootstrap -->
      <link href='{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}' rel="stylesheet">
      <!-- Font Awesome -->
      <link href='{% static "vendors/font-awesome/css/font-awesome.min.css" %}' rel="stylesheet">
      <!-- NProgress -->
      <link href='{% static "vendors/nprogress/nprogress.css" %}' rel="stylesheet">
      <!-- Big Calendar-->
      <link href='http://angular-ui.github.io/ui-calendar/bower_components/fullcalendar/dist/fullcalendar.css' rel="stylesheet">
      <link href='http://angular-ui.github.io/ui-calendar/demo/calendarDemo.css'>

      <!-- bootstrap-daterangepicker -->
      <link href='{% static "vendors/bootstrap-daterangepicker/daterangepicker.css" %}' rel="stylesheet">

      <!-- Custom Theme Style -->
      <link href='{% static "css/custom.min.css" %}' rel="stylesheet">
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link href="https://dalelotts.github.io/angularjs-bootstrap-datetimepicker/stylesheets/styles.css" rel="stylesheet"/>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js" ></script>
  </head>
  <body style="height: 100%;"  class="nav-md" ng-controller="baseController">
    <div style="height: 100%;"  class="container body">
      <div style="height: 100%;"  class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Easy Res</span></a>
            </div>

            <div class="clearfix"></div>
            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-pencil-square-o"></i> {% trans 'Reservations' %} <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/reservations">{% trans 'Reservations List' %}</a></li>
                      <li><a href="/reservations/create">{% trans 'Make Reservation' %}</a></li>
                    </ul>
                  </li>
                </ul>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-building-o"></i> {% trans 'Resources' %} <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="/resources">{% trans 'Resources List' %}</a></li>
                      {% if request.user.is_superuser %}
                          <li><a href="/resources/create">{% trans 'Add Resource' %}</a></li>
                      {% endif %}
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt="">{{request.user.first_name}} {{request.user.last_name}}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li><a href="/accounts/settings/">{% trans 'Settings' %}</a></li>
                    <li><a href="/logout/"><i class="fa fa-sign-out pull-right"></i>  {% trans 'Log Out' %} </a></li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" style="height: 100%;"  role="main">

          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                {% block content %}{% endblock %}
            </div>

          </div>
          <br />


        </div>
        <!-- /page content -->


      </div>
    </div>

    {% block js %}
        <!-- jQuery -->
        <script src='{% static "vendors/jquery/dist/jquery.min.js" %}'></script>
        <!-- Bootstrap -->
        <script src='{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}'></script>


        <!-- AngularJs -->
        <script src="http://angular-ui.github.io/ui-calendar/bower_components/angular/angular.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src='{% static "vendors/moment/min/moment.min.js" %}'></script>
        <script src='{% static "vendors/bootstrap-daterangepicker/daterangepicker.js" %}'></script>

        <!-- Full Calendar -->
        <script src="http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.9.0.js"></script>
        <script src='{% static "js/calendar.js" %}'></script>
        <script src="http://angular-ui.github.io/ui-calendar/bower_components/fullcalendar/dist/fullcalendar.js"></script>

        <!-- Custom Theme Scripts -->
        <script src='{% static "js/custom.js" %}'></script>
        <script src='{% static "angular/module.js" %}'></script>



    {% endblock %}
	
  </body>
</html>

templates/reservation_details.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% load i18n %}

{% block content %}
<div class="row" ng-controller="reservationController">
   <input type="hidden" ng-init="id='{{object.id}}'">
   <div class="col-lg-5 col-md-7 col-sm-12 mb-4">
      <!-- Quick Post -->
      <div class="card card-small h-100">
         <div class="card-header border-bottom">
            <h6 class="m-0">New Reservation</h6>
         </div>
         <div class="card-body d-flex flex-column">
            <fieldset>
               <form>
                  <div class="form-group">
                     <label class="control-label" for="id_period"><label for="id_title">Title</label></label>
                     <div class="control-group">
                        <input ng-model='title'  class="form-control" id="id_title" maxlength="120" name="title" type="text" value="{[{reservation.title}]}">
                     </div>
                  </div>
                  <div class="form-group">
                     <label class="control-label" for="id_period"><label for="id_resource">Reservations</label></label>
                     <div class="control-group">
                        <select  class="form-control" id="id_resource" name="resource" required="" >
                           <option value="{[{selected_resource_id}]}" selected="selected">{[{selected_resource_title}]}</option>
                           <option  ng-repeat="resource in resources" value="{[{resource.id}]}">{[{resource.title}]}</option>
                        </select>
                     </div>
                  </div>
                  <div class="control-group">
                     <div class="controls">
                        <div class="input-prepend input-group">
                           <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                           <input type="text" ng-model='reservation_time' name="reservation_time" id="id_reservation_time" class="form-control" ng-model="reservation.reservation_time">
                        </div>
                     </div>
                  </div>
                  <div class="form-group">
                     <input ng-disabled="disableUpdate" ng-click="updateReservation(reservation.id)" type="submit" value="{% trans 'Update Reservation' %}" class="btn btn-primary">
                     <input ng-disabled="disableDelete" ng-click="deleteReservation(reservation.id)" type="submit" value="{% trans 'Delete Reservation' %}" class="btn btn-danger">
                  </div>
               </form>
            </fieldset>
         </div>
      </div>
      <!-- End Quick Post -->
   </div>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
    <script src='{% static "angular/services/reservations-service.js" %}'></script>
    <script src='{% static "angular/services/resources-service.js" %}'></script>
    <script src='{% static "angular/controllers/reservation-ctrl.js" %}'></script>

{% endblock %}

templates/reservation_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% load i18n %}

{% block content %}
<div class="page-title">
    <div class="title_left">
       <h3>{% trans 'New Reservation' %}</h3>
    </div>
</div>
<div class="row">
   <div class="col-lg-5 col-md-7 col-sm-12 mb-4">
      <!-- Quick Post -->
      <div class="card card-small h-100">

         <div class="card-body d-flex flex-column">
            <fieldset>
               <form method="post" role="form" action="/reservations/create/"> {% csrf_token %}
                  {% for field in form.visible_fields %}
                      {% if field.name != 'reservation_time' %}
                           <div class="form-group">
                              <label class="control-label" for="id_period">{{ field.label_tag }}</label>
                              <div class="control-group">
                                  {{ field }}
                               </div>
                          </div>
                      {% endif %}
                    {% endfor %}
                  <div class="control-group">
                     <div class="controls">
                        <div class="input-prepend input-group">
                           <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                           <input type="text" name="reservation_time" id="id_reservation_time" class="form-control" value="01/01/2016 - 01/25/2016" />
                        </div>
                     </div>
                  </div>
                  <div class="form-group">
                     <input type="submit" value="{% trans ' Make Reservation' %}" class="btn btn-primary" />
                  </div>
               </form>
            </fieldset>
         </div>
      </div>
      <!-- End Quick Post -->
   </div>
</div>
{% endblock content %}

templates/reservations_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<div class="page-title">
    <div class="title_left">
       <h3>{% trans 'Reservations List' %}</h3>
    </div>
</div>
<!-- End Page Header -->
         <div class="container" ng-controller="reservationsController">
             <div class="calendar" ng-model="eventSources" calendar="myCalendar1" ui-calendar="uiConfig.calendar"></div>
         </div>
{% endblock content %}

{% block js %}
    {{ block.super }}
    <script src='{% static "angular/services/reservations-service.js" %}'></script>
    <script src='{% static "angular/controllers/reservations-ctrl.js" %}'></script>
{% endblock %}

{% block head_css %}
    {{ block.super }}

{% endblock %}

templates/resource_form.html
{% extends "base.html" %}
{% load bootstrap %}
{% load i18n %}


{% block content %}
<div class="page-title">
    <div class="title_left">
       <h3>{% trans 'New Resource' %}</h3>
    </div>
</div>
<div class="row">
   <div class="col-lg-5 col-md-7 col-sm-12 mb-4">
      <!-- Quick Post -->
      <div class="card card-small h-100">
         <div class="card-body d-flex flex-column">
            <form method="post" role="form" action="/resources/create/">
               {{ form|bootstrap }}
               {% csrf_token %}
               <div class="form-group">
                  <input type="submit" value="{% trans 'Add Resource' %}" class="btn btn-primary" />
               </div>
            </form>
         </div>
      </div>
      <!-- End Quick Post -->
   </div>
</div>
{% endblock content %}

templates/resources_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<div ng-controller="resourceController">
<div class="page-title">
    <div class="title_left">
       <h3>{% trans 'Resources List' %}</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
   <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
         <div class="input-group">
            <input ng-model="filter" type="text" class="form-control" placeholder="{% trans 'Search by type or location...' %}">
            <span class="input-group-btn">
            <button class="btn btn-default" ng-click="filterResource()" type="button">Go!</button>
            </span>
         </div>
      </div>
   </div>
</div>
<div class="row" ng-show="resources">
   <div ng-repeat="res in resources" class="col-md-55">
      <div class="thumbnail" style="min-height: 268px;">
         <div class="image view view-first">
            <img style="width: 100%; display: block;" src="{[{res.image}]}" alt="image" />
            <div class="mask">
               <div class="tools tools-bottom">
                  <a href="/reservations/create/?resource_id={[{res.id}]}"><i class="fa fa-link"></i></a>
                  <a ng-show="'{{request.user.is_superuser}}'==='True'" href="" ng-click="deleteResource(res.id)"><i class="fa fa-times"></i></a>
               </div>
            </div>
         </div>
         <div class="caption">
            <p>{[{res.title}]}</p>
            <p>{% trans 'location' %}: {[{res.location}]}</p>
            <p>{% trans 'Maximum number of persons' %}: {[{res.max_person}]}</p>
         </div>
      </div>
   </div>
</div>
{% endblock content %}
{% block js %}
{{ block.super }}
<script src='{% static "angular/services/resources-service.js" %}'></script>
<script src='{% static "angular/controllers/resources-ctrl.js" %}'></script>
{% endblock %}

templates/settings.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% load i18n %}

{% block content %}
<div class="row">
   <div class="col-lg-5 col-md-7 col-sm-12 mb-4">
      <!-- Quick Post -->
      <div class="card card-small h-100">
         <div class="card-header border-bottom">
            <h6 class="m-0">{% trans 'Settings' %}</h6>
         </div>
         <div class="card-body d-flex flex-column">
            <fieldset>
               <form>
                  <div class="form-group">
                     <label class="control-label" for="id_period"><label for="id_title">{% trans 'Language' %}</label></label>
                      <select  class="form-control" id="id_code" name="code" required="" >
                         <option {% if language_code == 'en' %}selected="selected"{% endif %} value="en">{% trans 'English' %}</option>
                         <option {% if language_code == 'fr' %}selected="selected"{% endif %} value="fr">{% trans 'French' %}</option>

                      </select>
                  </div>
                  <div class="form-group">
                     <label class="control-label" for="id_period"><label for="id_resource">{% trans 'Time Zone' %}</label></label>
                     <div class="control-group">
                        <select  class="form-control" id="id_timeZone" name="timeZone" required="" >
                           {% for x, y in time_zones %}
                               <option   {% if time_zone == x %}selected="selected"{% endif %} value="{{y}}">{{x}}</option>
                           {% endfor %}
                        </select>
                     </div>
                  </div>
                  <div class="form-group">
                     <input type="submit"  ng-click="changeSettings()" value="{% trans 'Save Settings' %}" class="btn btn-primary">
                  </div>
               </form>
            </fieldset>
         </div>
      </div>
      <!-- End Quick Post -->
   </div>
</div>
{% endblock content %}